name: Its An Example to Define Variables

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:
env:
  Greeting: Hello

jobs:
  build: 
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v4
    - name: Run a one-line script
      run: echo "$Greeting, world"
  
  

